name: generate-k8s-manifests
description: Convert docker compose file into kubernetes manifests
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: vagrant version
    info: vagrant is not installed
command: 
  linux: |
    pwd
    hostname
    vagrant ssh -c 'kompose convert -f project/docker-compose.yaml -o project/manifests.yaml'
    vagrant ssh -c 'kubectl apply -f project/manifests.yaml'