name: incredible-vagrant-task
description: A very ultra mega complex but simple, incredible vagrant task for stackspot
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: vagrant version
    info: vagrant is not installed
command: 
  linux:
    vagrant up
